### ISSUE TITLE
Why im not on it

### ISSUE THREAD

**Issue by The-Graze** [DevModTeam/.github#1]
can join pls

**Comment by lunakittyyy** [comment]
no

**Comment by lunakittyyy** [comment]
[Scott the Woz No [lmVtBctjbUM].webm](https://github.com/DevModTeam/.github/assets/17483712/3f861b83-a455-4f81-813a-7fdb0c994141)

**Comment by The-Graze** [comment]
oki

**Comment by The-Graze** [comment]
:3
